apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocketbase

resources:
  - config-map.yaml
  - deployment.yaml
  - persistent-volume-claim.yaml
  - service.yaml
  - service-account.yaml
