---
apiVersion: v1
kind: Service
metadata:
  name: pocketbase
  labels:
    app: pocketbase
spec:
  type: NodePort
  selector:
    app: pocketbase
  ports:
  - name: http
    protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 31000
